/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticationSignUpIndexRouteImport } from './routes/authentication/sign-up/index'
import { Route as AuthenticationSignInIndexRouteImport } from './routes/authentication/sign-in/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSignUpIndexRoute =
  AuthenticationSignUpIndexRouteImport.update({
    id: '/authentication/sign-up/',
    path: '/authentication/sign-up/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationSignInIndexRoute =
  AuthenticationSignInIndexRouteImport.update({
    id: '/authentication/sign-in/',
    path: '/authentication/sign-in/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authentication/sign-in': typeof AuthenticationSignInIndexRoute
  '/authentication/sign-up': typeof AuthenticationSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authentication/sign-in': typeof AuthenticationSignInIndexRoute
  '/authentication/sign-up': typeof AuthenticationSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authentication/sign-in/': typeof AuthenticationSignInIndexRoute
  '/authentication/sign-up/': typeof AuthenticationSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/authentication/sign-in' | '/authentication/sign-up'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authentication/sign-in/'
    | '/authentication/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthenticationSignInIndexRoute: typeof AuthenticationSignInIndexRoute
  AuthenticationSignUpIndexRoute: typeof AuthenticationSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/sign-up/': {
      id: '/authentication/sign-up/'
      path: '/authentication/sign-up'
      fullPath: '/authentication/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/sign-in/': {
      id: '/authentication/sign-in/'
      path: '/authentication/sign-in'
      fullPath: '/authentication/sign-in'
      preLoaderRoute: typeof AuthenticationSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthenticationSignInIndexRoute: AuthenticationSignInIndexRoute,
  AuthenticationSignUpIndexRoute: AuthenticationSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
